//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursoProgramado
    {
        public int idcursoprog { get; set; }
        public int idcurso { get; set; }
        public decimal Vacantes { get; set; }
        public decimal Matriculados { get; set; }
        public decimal PreCursoProg { get; set; }
        public string Horario { get; set; }
        public decimal Activo { get; set; }
    
        public virtual curso curso { get; set; }
    }
}
