//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_list_equipos
    {
        public int intdetalleeq { get; set; }
        public string estado { get; set; }
        public Nullable<int> idEquipo { get; set; }
        public string codigo { get; set; }
    
        public virtual equipo equipo { get; set; }
    }
}
