//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appcongreso.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bdgenericEntities : DbContext
    {
        public bdgenericEntities()
            : base("name=bdgenericEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<alumnos> alumnos { get; set; }
        public virtual DbSet<ambiente> ambiente { get; set; }
        public virtual DbSet<aud_audit_modif> aud_audit_modif { get; set; }
        public virtual DbSet<ciclo> ciclo { get; set; }
        public virtual DbSet<costos_prod_imprenta> costos_prod_imprenta { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<detalle_list_equipos> detalle_list_equipos { get; set; }
        public virtual DbSet<detalle_organizadores> detalle_organizadores { get; set; }
        public virtual DbSet<equipo> equipo { get; set; }
        public virtual DbSet<listaequipos> listaequipos { get; set; }
        public virtual DbSet<organizadores> organizadores { get; set; }
        public virtual DbSet<parametros> parametros { get; set; }
        public virtual DbSet<sala> sala { get; set; }
        public virtual DbSet<sede> sede { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tarifa> tarifa { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<cursoProgramado> cursoProgramado { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<usp__parametros_valor_xnombre_Result> usp__parametros_valor_xnombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp__parametros_valor_xnombre_Result>("usp__parametros_valor_xnombre", nombreParameter);
        }
    
        public virtual int usp_actualizar_actividad_codigo(Nullable<int> id, string descripcion, Nullable<int> idlistaeq, Nullable<int> idsala, Nullable<int> idorganiz, string nombre, Nullable<System.DateTime> fec_inicio, Nullable<System.DateTime> fec_fin, string responsable, string codigo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var idlistaeqParameter = idlistaeq.HasValue ?
                new ObjectParameter("idlistaeq", idlistaeq) :
                new ObjectParameter("idlistaeq", typeof(int));
    
            var idsalaParameter = idsala.HasValue ?
                new ObjectParameter("idsala", idsala) :
                new ObjectParameter("idsala", typeof(int));
    
            var idorganizParameter = idorganiz.HasValue ?
                new ObjectParameter("idorganiz", idorganiz) :
                new ObjectParameter("idorganiz", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fec_inicioParameter = fec_inicio.HasValue ?
                new ObjectParameter("fec_inicio", fec_inicio) :
                new ObjectParameter("fec_inicio", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_actividad_codigo", idParameter, descripcionParameter, idlistaeqParameter, idsalaParameter, idorganizParameter, nombreParameter, fec_inicioParameter, fec_finParameter, responsableParameter, codigoParameter);
        }
    
        public virtual int usp_actualizar_actividad_id(Nullable<int> id, string descripcion, Nullable<int> idlistaeq, Nullable<int> idsala, Nullable<int> idorganiz, string nombre, Nullable<System.DateTime> fec_inicio, Nullable<System.DateTime> fec_fin, string responsable)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var idlistaeqParameter = idlistaeq.HasValue ?
                new ObjectParameter("idlistaeq", idlistaeq) :
                new ObjectParameter("idlistaeq", typeof(int));
    
            var idsalaParameter = idsala.HasValue ?
                new ObjectParameter("idsala", idsala) :
                new ObjectParameter("idsala", typeof(int));
    
            var idorganizParameter = idorganiz.HasValue ?
                new ObjectParameter("idorganiz", idorganiz) :
                new ObjectParameter("idorganiz", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fec_inicioParameter = fec_inicio.HasValue ?
                new ObjectParameter("fec_inicio", fec_inicio) :
                new ObjectParameter("fec_inicio", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_actividad_id", idParameter, descripcionParameter, idlistaeqParameter, idsalaParameter, idorganizParameter, nombreParameter, fec_inicioParameter, fec_finParameter, responsableParameter);
        }
    
        public virtual int usp_actualizar_alumno_dni(string ap_paterno, string ap_materno, string nombre, string telefono, string sexo, string correo, string dNI, string dirrecion, string tipo)
        {
            var ap_paternoParameter = ap_paterno != null ?
                new ObjectParameter("ap_paterno", ap_paterno) :
                new ObjectParameter("ap_paterno", typeof(string));
    
            var ap_maternoParameter = ap_materno != null ?
                new ObjectParameter("ap_materno", ap_materno) :
                new ObjectParameter("ap_materno", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var dirrecionParameter = dirrecion != null ?
                new ObjectParameter("dirrecion", dirrecion) :
                new ObjectParameter("dirrecion", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_alumno_dni", ap_paternoParameter, ap_maternoParameter, nombreParameter, telefonoParameter, sexoParameter, correoParameter, dNIParameter, dirrecionParameter, tipoParameter);
        }
    
        public virtual int usp_actualizar_costosimprenta(string codigo, Nullable<int> nro_libros, Nullable<int> nro_paginas, Nullable<decimal> largo, Nullable<decimal> ancho, Nullable<int> nro_pliegos, Nullable<int> nro_resmas, Nullable<int> nro_placas, Nullable<decimal> doblez, Nullable<decimal> alce, Nullable<decimal> corte_refilado, Nullable<decimal> encolado, Nullable<decimal> movilidad, Nullable<decimal> manejo_archivo, Nullable<decimal> best_color, Nullable<decimal> cif, Nullable<decimal> tinta, Nullable<decimal> total, string titulo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nro_librosParameter = nro_libros.HasValue ?
                new ObjectParameter("nro_libros", nro_libros) :
                new ObjectParameter("nro_libros", typeof(int));
    
            var nro_paginasParameter = nro_paginas.HasValue ?
                new ObjectParameter("nro_paginas", nro_paginas) :
                new ObjectParameter("nro_paginas", typeof(int));
    
            var largoParameter = largo.HasValue ?
                new ObjectParameter("largo", largo) :
                new ObjectParameter("largo", typeof(decimal));
    
            var anchoParameter = ancho.HasValue ?
                new ObjectParameter("ancho", ancho) :
                new ObjectParameter("ancho", typeof(decimal));
    
            var nro_pliegosParameter = nro_pliegos.HasValue ?
                new ObjectParameter("nro_pliegos", nro_pliegos) :
                new ObjectParameter("nro_pliegos", typeof(int));
    
            var nro_resmasParameter = nro_resmas.HasValue ?
                new ObjectParameter("nro_resmas", nro_resmas) :
                new ObjectParameter("nro_resmas", typeof(int));
    
            var nro_placasParameter = nro_placas.HasValue ?
                new ObjectParameter("nro_placas", nro_placas) :
                new ObjectParameter("nro_placas", typeof(int));
    
            var doblezParameter = doblez.HasValue ?
                new ObjectParameter("doblez", doblez) :
                new ObjectParameter("doblez", typeof(decimal));
    
            var alceParameter = alce.HasValue ?
                new ObjectParameter("alce", alce) :
                new ObjectParameter("alce", typeof(decimal));
    
            var corte_refiladoParameter = corte_refilado.HasValue ?
                new ObjectParameter("corte_refilado", corte_refilado) :
                new ObjectParameter("corte_refilado", typeof(decimal));
    
            var encoladoParameter = encolado.HasValue ?
                new ObjectParameter("encolado", encolado) :
                new ObjectParameter("encolado", typeof(decimal));
    
            var movilidadParameter = movilidad.HasValue ?
                new ObjectParameter("movilidad", movilidad) :
                new ObjectParameter("movilidad", typeof(decimal));
    
            var manejo_archivoParameter = manejo_archivo.HasValue ?
                new ObjectParameter("manejo_archivo", manejo_archivo) :
                new ObjectParameter("manejo_archivo", typeof(decimal));
    
            var best_colorParameter = best_color.HasValue ?
                new ObjectParameter("best_color", best_color) :
                new ObjectParameter("best_color", typeof(decimal));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            var tintaParameter = tinta.HasValue ?
                new ObjectParameter("tinta", tinta) :
                new ObjectParameter("tinta", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_costosimprenta", codigoParameter, nro_librosParameter, nro_paginasParameter, largoParameter, anchoParameter, nro_pliegosParameter, nro_resmasParameter, nro_placasParameter, doblezParameter, alceParameter, corte_refiladoParameter, encoladoParameter, movilidadParameter, manejo_archivoParameter, best_colorParameter, cifParameter, tintaParameter, totalParameter, tituloParameter);
        }
    
        public virtual int usp_actualizar_equipo(Nullable<int> idEquipo, string nombre, string sO, string procesador, string rAM, string tarjetaMadre)
        {
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("idEquipo", idEquipo) :
                new ObjectParameter("idEquipo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var sOParameter = sO != null ?
                new ObjectParameter("SO", sO) :
                new ObjectParameter("SO", typeof(string));
    
            var procesadorParameter = procesador != null ?
                new ObjectParameter("Procesador", procesador) :
                new ObjectParameter("Procesador", typeof(string));
    
            var rAMParameter = rAM != null ?
                new ObjectParameter("RAM", rAM) :
                new ObjectParameter("RAM", typeof(string));
    
            var tarjetaMadreParameter = tarjetaMadre != null ?
                new ObjectParameter("TarjetaMadre", tarjetaMadre) :
                new ObjectParameter("TarjetaMadre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_equipo", idEquipoParameter, nombreParameter, sOParameter, procesadorParameter, rAMParameter, tarjetaMadreParameter);
        }
    
        public virtual int usp_actualizar_sala_id(Nullable<int> idsala, string nombre, string ubicacion, Nullable<int> capacidad, string tipo_sala)
        {
            var idsalaParameter = idsala.HasValue ?
                new ObjectParameter("idsala", idsala) :
                new ObjectParameter("idsala", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("capacidad", capacidad) :
                new ObjectParameter("capacidad", typeof(int));
    
            var tipo_salaParameter = tipo_sala != null ?
                new ObjectParameter("tipo_sala", tipo_sala) :
                new ObjectParameter("tipo_sala", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_sala_id", idsalaParameter, nombreParameter, ubicacionParameter, capacidadParameter, tipo_salaParameter);
        }
    
        public virtual int usp_actualizar_usuario(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_usuario", usuarioParameter, claveParameter);
        }
    
        public virtual int usp_actualizar_valor_param(Nullable<decimal> valor, string nombre)
        {
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(decimal));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_valor_param", valorParameter, nombreParameter);
        }
    
        public virtual int usp_borrar_det_list_equipos(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_det_list_equipos", codigoParameter);
        }
    
        public virtual int usp_borrar_det_organizadores(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_borrar_det_organizadores", codigoParameter);
        }
    
        public virtual ObjectResult<usp_buscar_actividad_codigo_Result> usp_buscar_actividad_codigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_buscar_actividad_codigo_Result>("usp_buscar_actividad_codigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_buscar_alumno_codigo_Result> usp_buscar_alumno_codigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_buscar_alumno_codigo_Result>("usp_buscar_alumno_codigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_buscar_alumno_id_Result> usp_buscar_alumno_id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_buscar_alumno_id_Result>("usp_buscar_alumno_id", idParameter);
        }
    
        public virtual ObjectResult<usp_BusquedaActividadforDescripcion_Result> usp_BusquedaActividadforDescripcion(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BusquedaActividadforDescripcion_Result>("usp_BusquedaActividadforDescripcion", descripcionParameter);
        }
    
        public virtual ObjectResult<usp_BusquedaActividadforFecha_Result> usp_BusquedaActividadforFecha(Nullable<System.DateTime> fec1)
        {
            var fec1Parameter = fec1.HasValue ?
                new ObjectParameter("fec1", fec1) :
                new ObjectParameter("fec1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BusquedaActividadforFecha_Result>("usp_BusquedaActividadforFecha", fec1Parameter);
        }
    
        public virtual ObjectResult<usp_costos_prod_imprenta_datos_Result> usp_costos_prod_imprenta_datos(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_costos_prod_imprenta_datos_Result>("usp_costos_prod_imprenta_datos", codigoParameter);
        }
    
        public virtual int usp_eliminar_actividad_codigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_actividad_codigo", codigoParameter);
        }
    
        public virtual int usp_eliminar_actividad_id(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_actividad_id", idParameter);
        }
    
        public virtual int usp_eliminar_alumno_dni(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_alumno_dni", dNIParameter);
        }
    
        public virtual int usp_eliminar_alumno_id(Nullable<int> idalumno)
        {
            var idalumnoParameter = idalumno.HasValue ?
                new ObjectParameter("idalumno", idalumno) :
                new ObjectParameter("idalumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_alumno_id", idalumnoParameter);
        }
    
        public virtual int usp_eliminar_costosimprenta(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_costosimprenta", codigoParameter);
        }
    
        public virtual int usp_eliminar_equipo(Nullable<int> idEquipo)
        {
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("idEquipo", idEquipo) :
                new ObjectParameter("idEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_equipo", idEquipoParameter);
        }
    
        public virtual int usp_eliminar_sala(Nullable<int> idsala)
        {
            var idsalaParameter = idsala.HasValue ?
                new ObjectParameter("idsala", idsala) :
                new ObjectParameter("idsala", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_sala", idsalaParameter);
        }
    
        public virtual int usp_eliminar_usuario(string idusuario)
        {
            var idusuarioParameter = idusuario != null ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_eliminar_usuario", idusuarioParameter);
        }
    
        public virtual ObjectResult<usp_equipo_datos_Result> usp_equipo_datos(Nullable<int> idEquipo)
        {
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("idEquipo", idEquipo) :
                new ObjectParameter("idEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_equipo_datos_Result>("usp_equipo_datos", idEquipoParameter);
        }
    
        public virtual ObjectResult<usp_equipo_datos_codigo_Result> usp_equipo_datos_codigo(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_equipo_datos_codigo_Result>("usp_equipo_datos_codigo", nombreParameter);
        }
    
        public virtual ObjectResult<usp_equipo_listar_all_Result> usp_equipo_listar_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_equipo_listar_all_Result>("usp_equipo_listar_all");
        }
    
        public virtual int usp_generarcodigo_actividad(ObjectParameter codigox)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_generarcodigo_actividad", codigox);
        }
    
        public virtual int usp_generarcodigo_organizadores(ObjectParameter codigox)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_generarcodigo_organizadores", codigox);
        }
    
        public virtual ObjectResult<usp_lista_equipos_Result> usp_lista_equipos(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_lista_equipos_Result>("usp_lista_equipos", codigoParameter);
        }
    
        public virtual ObjectResult<usp_lista_equipos_oficial_Result> usp_lista_equipos_oficial(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_lista_equipos_oficial_Result>("usp_lista_equipos_oficial", codigoParameter);
        }
    
        public virtual ObjectResult<usp_listaequipo_datos_codigo_Result> usp_listaequipo_datos_codigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listaequipo_datos_codigo_Result>("usp_listaequipo_datos_codigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_listaequipos_listar_all_Result> usp_listaequipos_listar_all(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listaequipos_listar_all_Result>("usp_listaequipos_listar_all", codigoParameter);
        }
    
        public virtual ObjectResult<usp_listar_actividades_all_Result> usp_listar_actividades_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_actividades_all_Result>("usp_listar_actividades_all");
        }
    
        public virtual ObjectResult<usp_listar_alumnos_all_Result> usp_listar_alumnos_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_alumnos_all_Result>("usp_listar_alumnos_all");
        }
    
        public virtual ObjectResult<usp_listar_alumnos_tipo_Result> usp_listar_alumnos_tipo(string tipo_alumno)
        {
            var tipo_alumnoParameter = tipo_alumno != null ?
                new ObjectParameter("tipo_alumno", tipo_alumno) :
                new ObjectParameter("tipo_alumno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_alumnos_tipo_Result>("usp_listar_alumnos_tipo", tipo_alumnoParameter);
        }
    
        public virtual ObjectResult<usp_listar_ambientes_all_Result> usp_listar_ambientes_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_ambientes_all_Result>("usp_listar_ambientes_all");
        }
    
        public virtual ObjectResult<usp_listar_curso_all_Result> usp_listar_curso_all(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_curso_all_Result>("usp_listar_curso_all", tipoParameter);
        }
    
        public virtual ObjectResult<usp_listar_curso_tipo_Result> usp_listar_curso_tipo(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_curso_tipo_Result>("usp_listar_curso_tipo", tipoParameter);
        }
    
        public virtual ObjectResult<usp_listar_salas_all_Result> usp_listar_salas_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_salas_all_Result>("usp_listar_salas_all");
        }
    
        public virtual ObjectResult<usp_listar_sede_all_Result> usp_listar_sede_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_sede_all_Result>("usp_listar_sede_all");
        }
    
        public virtual ObjectResult<usp_listar_tipoeventos_Result> usp_listar_tipoeventos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_tipoeventos_Result>("usp_listar_tipoeventos");
        }
    
        public virtual ObjectResult<usp_organizadores_datos_codigo_Result> usp_organizadores_datos_codigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_organizadores_datos_codigo_Result>("usp_organizadores_datos_codigo", codigoParameter);
        }
    
        public virtual ObjectResult<usp_organizadores_oficial_Result> usp_organizadores_oficial(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_organizadores_oficial_Result>("usp_organizadores_oficial", codigoParameter);
        }
    
        public virtual ObjectResult<usp_organizadores_oficial_all_Result> usp_organizadores_oficial_all(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_organizadores_oficial_all_Result>("usp_organizadores_oficial_all", codigoParameter);
        }
    
        public virtual ObjectResult<usp_parametros_valor_xnombre_Result> usp_parametros_valor_xnombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_parametros_valor_xnombre_Result>("usp_parametros_valor_xnombre", nombreParameter);
        }
    
        public virtual int usp_participantes_datos(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_participantes_datos", dNIParameter);
        }
    
        public virtual int usp_registrar_actividad_oficial(string nombre, string codigo, string descripcion, string responsable, string rol_creacion, Nullable<System.DateTime> fec_inicio, Nullable<System.DateTime> fec_fin, string tipoevento, string lugar, string certificado, string inscripcion, Nullable<int> idlistaeq, Nullable<int> idsala, Nullable<int> idsede, Nullable<int> idambiente, string justificacion, string objetivos, Nullable<int> horas, Nullable<int> idorganiz)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var rol_creacionParameter = rol_creacion != null ?
                new ObjectParameter("rol_creacion", rol_creacion) :
                new ObjectParameter("rol_creacion", typeof(string));
    
            var fec_inicioParameter = fec_inicio.HasValue ?
                new ObjectParameter("fec_inicio", fec_inicio) :
                new ObjectParameter("fec_inicio", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            var tipoeventoParameter = tipoevento != null ?
                new ObjectParameter("tipoevento", tipoevento) :
                new ObjectParameter("tipoevento", typeof(string));
    
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var certificadoParameter = certificado != null ?
                new ObjectParameter("certificado", certificado) :
                new ObjectParameter("certificado", typeof(string));
    
            var inscripcionParameter = inscripcion != null ?
                new ObjectParameter("inscripcion", inscripcion) :
                new ObjectParameter("inscripcion", typeof(string));
    
            var idlistaeqParameter = idlistaeq.HasValue ?
                new ObjectParameter("idlistaeq", idlistaeq) :
                new ObjectParameter("idlistaeq", typeof(int));
    
            var idsalaParameter = idsala.HasValue ?
                new ObjectParameter("idsala", idsala) :
                new ObjectParameter("idsala", typeof(int));
    
            var idsedeParameter = idsede.HasValue ?
                new ObjectParameter("idsede", idsede) :
                new ObjectParameter("idsede", typeof(int));
    
            var idambienteParameter = idambiente.HasValue ?
                new ObjectParameter("idambiente", idambiente) :
                new ObjectParameter("idambiente", typeof(int));
    
            var justificacionParameter = justificacion != null ?
                new ObjectParameter("justificacion", justificacion) :
                new ObjectParameter("justificacion", typeof(string));
    
            var objetivosParameter = objetivos != null ?
                new ObjectParameter("objetivos", objetivos) :
                new ObjectParameter("objetivos", typeof(string));
    
            var horasParameter = horas.HasValue ?
                new ObjectParameter("horas", horas) :
                new ObjectParameter("horas", typeof(int));
    
            var idorganizParameter = idorganiz.HasValue ?
                new ObjectParameter("idorganiz", idorganiz) :
                new ObjectParameter("idorganiz", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_actividad_oficial", nombreParameter, codigoParameter, descripcionParameter, responsableParameter, rol_creacionParameter, fec_inicioParameter, fec_finParameter, tipoeventoParameter, lugarParameter, certificadoParameter, inscripcionParameter, idlistaeqParameter, idsalaParameter, idsedeParameter, idambienteParameter, justificacionParameter, objetivosParameter, horasParameter, idorganizParameter);
        }
    
        public virtual int usp_registrar_alumno(string ap_paterno, string ap_materno, string nombre, string telefono, string sexo, string correo, string dNI, string carrera, string direccion, string tipo_alumno)
        {
            var ap_paternoParameter = ap_paterno != null ?
                new ObjectParameter("ap_paterno", ap_paterno) :
                new ObjectParameter("ap_paterno", typeof(string));
    
            var ap_maternoParameter = ap_materno != null ?
                new ObjectParameter("ap_materno", ap_materno) :
                new ObjectParameter("ap_materno", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var carreraParameter = carrera != null ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var tipo_alumnoParameter = tipo_alumno != null ?
                new ObjectParameter("tipo_alumno", tipo_alumno) :
                new ObjectParameter("tipo_alumno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_alumno", ap_paternoParameter, ap_maternoParameter, nombreParameter, telefonoParameter, sexoParameter, correoParameter, dNIParameter, carreraParameter, direccionParameter, tipo_alumnoParameter);
        }
    
        public virtual int usp_registrar_costos_prod_imprenta(string codigo, Nullable<int> nro_libros, Nullable<int> nro_paginas, Nullable<decimal> largo, Nullable<decimal> ancho, Nullable<int> nro_pliegos, Nullable<int> nro_resmas, Nullable<int> nro_placas, Nullable<decimal> doblez, Nullable<decimal> alce, Nullable<decimal> corte_refilado, Nullable<decimal> encolado, Nullable<decimal> movilidad, Nullable<decimal> manejo_archivo, Nullable<decimal> best_color, Nullable<decimal> cif, Nullable<decimal> tinta, Nullable<decimal> total, string titulo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nro_librosParameter = nro_libros.HasValue ?
                new ObjectParameter("nro_libros", nro_libros) :
                new ObjectParameter("nro_libros", typeof(int));
    
            var nro_paginasParameter = nro_paginas.HasValue ?
                new ObjectParameter("nro_paginas", nro_paginas) :
                new ObjectParameter("nro_paginas", typeof(int));
    
            var largoParameter = largo.HasValue ?
                new ObjectParameter("largo", largo) :
                new ObjectParameter("largo", typeof(decimal));
    
            var anchoParameter = ancho.HasValue ?
                new ObjectParameter("ancho", ancho) :
                new ObjectParameter("ancho", typeof(decimal));
    
            var nro_pliegosParameter = nro_pliegos.HasValue ?
                new ObjectParameter("nro_pliegos", nro_pliegos) :
                new ObjectParameter("nro_pliegos", typeof(int));
    
            var nro_resmasParameter = nro_resmas.HasValue ?
                new ObjectParameter("nro_resmas", nro_resmas) :
                new ObjectParameter("nro_resmas", typeof(int));
    
            var nro_placasParameter = nro_placas.HasValue ?
                new ObjectParameter("nro_placas", nro_placas) :
                new ObjectParameter("nro_placas", typeof(int));
    
            var doblezParameter = doblez.HasValue ?
                new ObjectParameter("doblez", doblez) :
                new ObjectParameter("doblez", typeof(decimal));
    
            var alceParameter = alce.HasValue ?
                new ObjectParameter("alce", alce) :
                new ObjectParameter("alce", typeof(decimal));
    
            var corte_refiladoParameter = corte_refilado.HasValue ?
                new ObjectParameter("corte_refilado", corte_refilado) :
                new ObjectParameter("corte_refilado", typeof(decimal));
    
            var encoladoParameter = encolado.HasValue ?
                new ObjectParameter("encolado", encolado) :
                new ObjectParameter("encolado", typeof(decimal));
    
            var movilidadParameter = movilidad.HasValue ?
                new ObjectParameter("movilidad", movilidad) :
                new ObjectParameter("movilidad", typeof(decimal));
    
            var manejo_archivoParameter = manejo_archivo.HasValue ?
                new ObjectParameter("manejo_archivo", manejo_archivo) :
                new ObjectParameter("manejo_archivo", typeof(decimal));
    
            var best_colorParameter = best_color.HasValue ?
                new ObjectParameter("best_color", best_color) :
                new ObjectParameter("best_color", typeof(decimal));
    
            var cifParameter = cif.HasValue ?
                new ObjectParameter("cif", cif) :
                new ObjectParameter("cif", typeof(decimal));
    
            var tintaParameter = tinta.HasValue ?
                new ObjectParameter("tinta", tinta) :
                new ObjectParameter("tinta", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(decimal));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_costos_prod_imprenta", codigoParameter, nro_librosParameter, nro_paginasParameter, largoParameter, anchoParameter, nro_pliegosParameter, nro_resmasParameter, nro_placasParameter, doblezParameter, alceParameter, corte_refiladoParameter, encoladoParameter, movilidadParameter, manejo_archivoParameter, best_colorParameter, cifParameter, tintaParameter, totalParameter, tituloParameter);
        }
    
        public virtual int usp_registrar_curso(string nombre, string tipo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_curso", nombreParameter, tipoParameter);
        }
    
        public virtual int usp_registrar_det_list_equipos(Nullable<int> idEquipo, string codigo)
        {
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("idEquipo", idEquipo) :
                new ObjectParameter("idEquipo", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_det_list_equipos", idEquipoParameter, codigoParameter);
        }
    
        public virtual int usp_registrar_det_org(string dNI, string codigo)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_det_org", dNIParameter, codigoParameter);
        }
    
        public virtual int usp_registrar_equipo(string nombre, string sO, string procesador, string rAM, string tMADRE)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var sOParameter = sO != null ?
                new ObjectParameter("SO", sO) :
                new ObjectParameter("SO", typeof(string));
    
            var procesadorParameter = procesador != null ?
                new ObjectParameter("Procesador", procesador) :
                new ObjectParameter("Procesador", typeof(string));
    
            var rAMParameter = rAM != null ?
                new ObjectParameter("RAM", rAM) :
                new ObjectParameter("RAM", typeof(string));
    
            var tMADREParameter = tMADRE != null ?
                new ObjectParameter("TMADRE", tMADRE) :
                new ObjectParameter("TMADRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_equipo", nombreParameter, sOParameter, procesadorParameter, rAMParameter, tMADREParameter);
        }
    
        public virtual int usp_registrar_lista_equipos(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_lista_equipos", codigoParameter);
        }
    
        public virtual int usp_registrar_organizadores(string codigo, Nullable<int> iddetorg, ObjectParameter idorganiz)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var iddetorgParameter = iddetorg.HasValue ?
                new ObjectParameter("iddetorg", iddetorg) :
                new ObjectParameter("iddetorg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_organizadores", codigoParameter, iddetorgParameter, idorganiz);
        }
    
        public virtual int usp_registrar_sala(string nombre, string ubicacion, Nullable<int> capacidad, string rol_creacion, string tipo_Sala)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("capacidad", capacidad) :
                new ObjectParameter("capacidad", typeof(int));
    
            var rol_creacionParameter = rol_creacion != null ?
                new ObjectParameter("rol_creacion", rol_creacion) :
                new ObjectParameter("rol_creacion", typeof(string));
    
            var tipo_SalaParameter = tipo_Sala != null ?
                new ObjectParameter("tipo_Sala", tipo_Sala) :
                new ObjectParameter("tipo_Sala", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_sala", nombreParameter, ubicacionParameter, capacidadParameter, rol_creacionParameter, tipo_SalaParameter);
        }
    
        public virtual int usp_registrar_sede(string nombre, string direccion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_sede", nombreParameter, direccionParameter);
        }
    
        public virtual int usp_registrar_usuario(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_usuario", usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<usp_sala_datos_Result> usp_sala_datos(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_sala_datos_Result>("usp_sala_datos", nombreParameter);
        }
    
        public virtual ObjectResult<usp_usuarios_listar_all_Result> usp_usuarios_listar_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_usuarios_listar_all_Result>("usp_usuarios_listar_all");
        }
    
        public virtual ObjectResult<usp_ValidaUsuario_Result> usp_ValidaUsuario(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ValidaUsuario_Result>("usp_ValidaUsuario", usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<usp_buscar_alumno_dni_Result> usp_buscar_alumno_dni(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_buscar_alumno_dni_Result>("usp_buscar_alumno_dni", dNIParameter);
        }
    
        public virtual int usp_actualizar_usuario_user(string usuario, string clave, byte[] foto)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_actualizar_usuario_user", usuarioParameter, claveParameter, fotoParameter);
        }
    
        public virtual ObjectResult<usp_buscar_usuario_nombre_Result> usp_buscar_usuario_nombre(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_buscar_usuario_nombre_Result>("usp_buscar_usuario_nombre", usuarioParameter);
        }
    }
}
